### ISSUE TITLE
[Request] Audio volume adjustment

### ISSUE THREAD

**Issue by grillow** [ivabus/lonelyradio#2]
It would be nice to be able to adjust volume in `monoclient` using, for example, `playerctl volume` command. Or at least if it appeared in `pulsemixer` for manual volume control.
Or is there a way to adjust volume currently? Am I missing something?

**Comment by ivabus** [comment]
There is no way to adjust volume at the moment, but I will implement something in the next release

**Comment by ivabus** [comment]
I've implemented manual adjustments to volume via keyboard keys (Up and Down, Q for exit) in `monoclient` and `monolib` ([volume](https://github.com/ivabus/lonelyradio/tree/volume) branch). ~I will research into MPRIS later~ MPRIS (D-Bus player interface) support will be added later

**Comment by ivabus** [comment]
Added untested MPRIS functionality (I don't have Linux machine on hand right now, so please provide feedback) to [volume](https://github.com/ivabus/lonelyradio/tree/volume) branch.

**Comment by grillow** [comment]
The keyboard keys option really works! Thanks

**Comment by ivabus** [comment]
Nice. Closing issue for now. MPRIS support will be added eventually.

**Comment by ivabus** [comment]
0.5.0 released with manual volume control in both CLI and GUI (Slint) clients
